<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Krish" ignored="0" name="Banking App Test" tests="3" failures="2" timestamp="31 Jan 2021 07:32:07 GMT" time="116.994" errors="0">
  <testcase name="addnewcustomer" time="36.094" classname="com.inetBanking.functionalTestCases.TC_AddNewCustomer_003"/>
  <testcase name="addnewcustomer" time="36.144" classname="com.inetBanking.functionalTestCases.TC_AddNewCustomer_003">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at java.util.regex.Matcher.getTextLength(Matcher.java:1283)
at java.util.regex.Matcher.reset(Matcher.java:309)
at java.util.regex.Matcher.<init>(Matcher.java:229)
at java.util.regex.Pattern.matcher(Pattern.java:1093)
at com.aventstack.extentreports.utils.ExceptionUtil.getExceptionHeadline(ExceptionUtil.java:26)
at com.aventstack.extentreports.ExtentTest.log(ExtentTest.java:407)
at com.aventstack.extentreports.ExtentTest.log(ExtentTest.java:425)
at com.inetBanking.utilities.ListnerReporting.onTestSuccess(ListnerReporting.java:59)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- addnewcustomer -->
  <testcase name="loginTest01" time="9.038" classname="com.inetBanking.functionalTestCases.TC_testcase_001">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.inetBanking.functionalTestCases.TC_testcase_001.loginTest01(TC_testcase_001.java:41)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- loginTest01 -->
</testsuite> <!-- Banking App Test -->
